# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.8 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Location where the package is installed by 'make install' 
prefix ?= /usr/local

# Destination root (/ is used if empty) 
DESTDIR ?= 

# C++ compiler 
CXX = g++

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 

# Location and arguments of wx-config script 
WX_CONFIG ?= wx-config

# C++ flags to use with wxWidgets code 
WX_CXXFLAGS ?= `$(WX_CONFIG) --cxxflags`



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
AGENDER_CXXFLAGS =   $(WX_CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS)
AGENDER_OBJECTS =  \
	Agender_AgenderIPC.o \
	Agender_AgenderApp.o \
	Agender_AgenderMain.o \
	Agender_AgenderTray.o \
	Agender_AgenderCal.o

### Conditionally set variables: ###



### Targets: ###

all: Agender mo

install: install_Agender
	$(INSTALL) -d $(DESTDIR)$(prefix)/share/applications
	(cd . ; $(INSTALL) -m 644  share/Agender.desktop $(DESTDIR)$(prefix)/share/applications)
	$(INSTALL) -d $(DESTDIR)$(prefix)/share/pixmaps
	(cd . ; $(INSTALL) -m 644  share/Agender.png $(DESTDIR)$(prefix)/share/pixmaps)

uninstall: uninstall_Agender
	(cd $(DESTDIR)$(prefix)/share/applications ; rm -f Agender.desktop)
	(cd $(DESTDIR)$(prefix)/share/pixmaps ; rm -f Agender.png)

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f Agender

Agender: $(AGENDER_OBJECTS)
	$(CXX) -o $@ $(AGENDER_OBJECTS)   `$(WX_CONFIG) --libs net,richtext,adv,core,base` $(LDFLAGS)

install_Agender: Agender
	$(INSTALL) -d $(DESTDIR)$(prefix)/bin
	install -c Agender $(DESTDIR)$(prefix)/bin

uninstall_Agender: 
	rm -f $(DESTDIR)$(prefix)/bin/Agender

dist: clean topdist srcdist sharedist wxsmithdist podist apspecdist
	cd ./Agender-1.1.6;bakefile -f autoconf Agender.bkl
	cd ./Agender-1.1.6;bakefilize --copy
	cd ./Agender-1.1.6;aclocal
	cd ./Agender-1.1.6;autoconf
	tar -jcf Agender-1.1.6.tar.bz2 Agender-1.1.6
	rm -rf ./Agender-1.1.6

topdist: 
	@mkdir -p ./Agender-1.1.6/
	@for f in *.spec.in *.bkl *.nsi configure.in gpl-3.0.txt Readme.txt; do \
	if test ! -f ./Agender-1.1.6//$$f -a ! -d ./Agender-1.1.6//$$f ; \
	then x=yep ; \
	else x=`find .//$$f -newer ./Agender-1.1.6//$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf .//$$f ./Agender-1.1.6/ ;; \
	esac; \
	done

srcdist: 
	@mkdir -p ./Agender-1.1.6/src
	@for f in *.h *.cpp *.rc *.xpm *.ico *.cbp; do \
	if test ! -f ./Agender-1.1.6/src/$$f -a ! -d ./Agender-1.1.6/src/$$f ; \
	then x=yep ; \
	else x=`find ./src//$$f -newer ./Agender-1.1.6/src/$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf ./src//$$f ./Agender-1.1.6/src ;; \
	esac; \
	done

sharedist: 
	@mkdir -p ./Agender-1.1.6/share/
	@for f in ./share/*; do \
	if test ! -f ./Agender-1.1.6/share//$$f -a ! -d ./Agender-1.1.6/share//$$f ; \
	then x=yep ; \
	else x=`find .//$$f -newer ./Agender-1.1.6/share//$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf .//$$f ./Agender-1.1.6/share/ ;; \
	esac; \
	done

wxsmithdist: 
	@mkdir -p ./Agender-1.1.6/src/wxsmith/
	@for f in ./src/wxsmith/*; do \
	if test ! -f ./Agender-1.1.6/src/wxsmith//$$f -a ! -d ./Agender-1.1.6/src/wxsmith//$$f ; \
	then x=yep ; \
	else x=`find ./$$f -newer ./Agender-1.1.6/src/wxsmith//$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf ./$$f ./Agender-1.1.6/src/wxsmith/ ;; \
	esac; \
	done

podist: 
	@mkdir -p ./Agender-1.1.6/po
	@for f in *.po; do \
	if test ! -f ./Agender-1.1.6/po/$$f -a ! -d ./Agender-1.1.6/po/$$f ; \
	then x=yep ; \
	else x=`find ./po/$$f -newer ./Agender-1.1.6/po/$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf ./po/$$f ./Agender-1.1.6/po ;; \
	esac; \
	done

apspecdist: 
	@mkdir -p ./Agender-1.1.6/autopackage/
	@for f in autopackage/*.apspec.in; do \
	if test ! -f ./Agender-1.1.6/autopackage//$$f -a ! -d ./Agender-1.1.6/autopackage//$$f ; \
	then x=yep ; \
	else x=`find ./$$f -newer ./Agender-1.1.6/autopackage//$$f -print` ; \
	fi; \
	case "$$x" in ?*) \
	cp -pRf ./$$f ./Agender-1.1.6/autopackage/ ;; \
	esac; \
	done

mo: 
	msgfmt po/es.po -o po/es.mo
	msgfmt po/de.po -o po/de.mo
	msgfmt po/ja.po -o po/ja.mo

rpm: dist
	rpmdev-setuptree
	mv Agender-1.1.6.tar.bz2 ~/rpmbuild/SOURCES/
	cd ~/rpmbuild/SOURCES/;tar -xf Agender-1.1.6.tar.bz2
	cd ~/rpmbuild/SOURCES/Agender-1.1.6;./configure
	cp ~/rpmbuild/SOURCES/Agender-1.1.6/Agender.spec ~/rpmbuild/SPECS/
	cp ~/rpmbuild/SOURCES/Agender-1.1.6/src/Agender.xpm ~/rpmbuild/SOURCES/
	rm -rf ~/rpmbuild/SOURCES/Agender-1.1.6
	rpmbuild -ba ~/rpmbuild/SPECS/Agender.spec

Agender_AgenderIPC.o: ./src/AgenderIPC.cpp
	$(CXX) -c -o $@ $(AGENDER_CXXFLAGS) $(CPPDEPS) $<

Agender_AgenderApp.o: ./src/AgenderApp.cpp
	$(CXX) -c -o $@ $(AGENDER_CXXFLAGS) $(CPPDEPS) $<

Agender_AgenderMain.o: ./src/AgenderMain.cpp
	$(CXX) -c -o $@ $(AGENDER_CXXFLAGS) $(CPPDEPS) $<

Agender_AgenderTray.o: ./src/AgenderTray.cpp
	$(CXX) -c -o $@ $(AGENDER_CXXFLAGS) $(CPPDEPS) $<

Agender_AgenderCal.o: ./src/AgenderCal.cpp
	$(CXX) -c -o $@ $(AGENDER_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_Agender uninstall_Agender topdist \
	srcdist sharedist wxsmithdist podist apspecdist


# Dependencies tracking:
-include ./*.d
